version: '3.7'
services:
    db: 
        image: mysql:5.7
        container_name: railsdbv3
        restart: always
        volumes:
            - db_data:/var/lib/mysql     
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    app: 
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: railsphpadminv3
        restart: always
        ports:
            - "3333:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
volumes:
    db_data: {}